USE [master]
GO

/****** Object:  Database [TestTask]    Script Date: 22.11.2024 15:53:59 ******/
CREATE DATABASE [TestTask]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestTask', FILENAME = N'C:\Users\Полина\TestTask.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestTask_log', FILENAME = N'C:\Users\Полина\TestTask_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestTask].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestTask] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestTask] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestTask] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestTask] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestTask] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestTask] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestTask] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestTask] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestTask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestTask] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestTask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestTask] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestTask] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestTask] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestTask] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestTask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestTask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestTask] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestTask] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestTask] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestTask] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestTask] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestTask] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestTask] SET  MULTI_USER 
GO

ALTER DATABASE [TestTask] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestTask] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestTask] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestTask] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestTask] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestTask] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestTask] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestTask] SET  READ_WRITE 
GO

